
import Head from "next/head";

export default function Login() {
  return (
    <>
      {/* bg */}
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-screen w-screen bg-[#e2e2e2] ">
          {/* login form container */}
          <div className="flex h-full w-full flex-col items-center justify-center ">
            {/* login form */}
            <div className="flex w-1/3  flex-col items-center justify-center rounded-md bg-white  p-4 shadow-2xl">
              {/* login form title */}
              <h1 className="text-4xl font-semibold text-[#011627]">
                Iniciar Sesion
              </h1>
              {/* login form inputs */}
              <div className="flex w-full flex-col items-center justify-center ">
                {/* email input */}
                <h1 className="w-full text-xl font-semibold text-[#011627]">
                  Email:
                </h1>
                <input
                  type="email"
                  className="my-2 w-full rounded-md p-2"
                  placeholder="Correo"
                />

                {/* password input */}
                <h1 className="w-full text-xl font-semibold text-[#011627]">
                  Contraseña:
                </h1>
                <input
                  type="password"
                  className="my-2 w-full rounded-md p-2"
                  placeholder="Contraseña"
                />
              </div>
              <div className="flex w-full flex-col gap-2  lg:flex-row lg:justify-between">
                {/* login button */}
                <button className=" my-2 w-full rounded-md bg-blue-700 p-3  font-semibold text-white hover:bg-blue-800 active:bg-blue-900">
                  Iniciar Sesion
                </button>
                {/* register button */}
                <button className=" my-2 w-full rounded-md bg-green-700 p-3  font-semibold text-white hover:bg-green-800 active:bg-green-900">
                  Registrarse
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
